spring:
  application:
    name: demorabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        concurrency: 1
        max-concurrency: 1
